[project]
name = "rent-project"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.smartcontract]
path = "contracts/smartcontract.clar"
depends_on = []

[contracts.smarthousing]
path = "contracts/smarthousing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
